---
- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true

- name: restart prometheus-node-exporter
  service:
    name: prometheus-node-exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true