- name: Download helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Add /usr/local/bin to system path in profile.d
  copy: 
    content: export PATH=$PATH:/usr/local/bin
    dest: /etc/profile.d/helm_path.sh
    force: no
  become: yes

- name: Make helm_path file executable
  file:
    path: /etc/profile.d/helm_path.sh
    mode: +x
  become: yes

- name: Add /usr/local/bin to system path 
  shell: /etc/profile.d/helm_path.sh
  args:
    executable: /bin/bash

- name: Add /usr/local/bin to system path in bashrc
  lineinfile:
    path: "{{localhome}}/.bashrc"
    line: export PATH=$PATH:/usr/local/bin

- name: Install Helm
  shell: "/tmp/get_helm.sh -v {{ helm_version }}"
  args:
    executable: /bin/bash

- name: Tidy up Helm script
  file:
    path: '/tmp/get_helm.sh'
    state: absent

- name: Add stable helm repo
  shell: |
    helm repo add stable {{helm_stable_repo_url}}
    helm repo update;