- name: Download helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install Helm
  shell: "/tmp/get_helm.sh -v {{ helm_version }}"
  args:
    executable: /bin/bash

- name: Tidy up Helm script
  file:
    path: '/tmp/get_helm.sh'
    state: absent

- name: Add stable helm repo
  shell: |
    helm repo add stable {{helm_stable_repo_url}}
    helm repo update;