---
- name: resolve platform specific vars
  include_vars: '{{ docker_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/../../vars'
  loop_control:
    loop_var: docker_vars

- name: install python3-pip
  apt:
    name:
      - python3-pip
  become: true

- name: install openshift in pip3
  pip:
    name: openshift
    executable: pip3

- include: remove.yml
- include: install.yml
