---

- name: set facts for helm
  set_fact:
    "user_home": "{{ lookup('env','HOME') }}"

- name: Reset Helm
  shell: helm reset
  become: yes
  ignore_errors: yes

- name: uninstall Tiller # should be unnecessary, but let's double-check
  shell: kubectl delete deployment.apps/tiller-deploy  service/tiller-deploy -n kube-system
  # become: yes
  ignore_errors: yes
    
- name: Find all helm-related files in previously known locations
  find:
    paths: "{{ minikube_install_dir }}"
    patterns: '{{ helm_name }}*'
    recurse: yes
  register: files_to_delete

- name: Remove all Helm files
  file:
    path: "{{ item.path }}"
    state: absent
  become: yes
  with_items: "{{ files_to_delete.files }}"

- name: Find alternative locations also
  shell: which helm
  register: helm_path
  ignore_errors: yes

- debug:
    msg: '{{ helm_path.stdout }}'
    verbosity: 1

- name: Remove if any helm executable still exists
  file:
    path: '{{ helm_path.stdout }}'
    state: absent
  become: yes
  
- name: Remove symlink
  file:
    path: '{{ minikube_install_dir }}/{{ helm_name }}'
    state: absent
  become: yes

- name: Remove config files
  file:
    path: '{{ user_home }}/.config/{{ helm_name }}'
    state: absent
  become: yes

- name: Remove plugin files
  file:
    path: "{{ item }}"
    state: absent
  become: yes
  with_items:
    - '{{ user_home }}/.local/share/{{ helm_name }}'
    - '{{ user_home }}/.helm'
