---

- name: set facts for helm
  set_fact:
    "user_home": "{{ lookup('env','HOME') }}"

- name: check helm installed
  stat:
    path: /usr/local/bin
  register: helm_binary

- name: check installed helm version
  shell: helm version --short
  register: helm_installed_version
  when: helm_binary.stat.exists == False

- name: Reset Helm
  shell: helm reset --force
  become: yes
  ignore_errors: yes
  when:
    - helm_binary.stat.exists 
    - helm_installed_version.stdout is defined and helm_installed_version.stdout[1] < 3

- name: uninstall Tiller
  ignore_errors: yes
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: tiller
        namespace: kube-system
    
- name: Find all helm-related files in previously known locations
  find:
    paths: "{{ minikube_install_dir }}"
    patterns: '{{ helm_name }}*'
    recurse: yes
  register: files_to_delete

- name: Remove all Helm files
  file:
    path: "{{ item.path }}"
    state: absent
  become: yes
  with_items: "{{ files_to_delete.files }}"

- name: Find alternative locations
  shell: which helm
  register: helm_path
  changed_when: false
  failed_when: helm_path.rc not in [0,1]

- name: Remove if any helm executable still exists
  become: yes
  file:
    path: '{{ helm_path.stdout }}'
    state: absent
  
- name: Remove symlink
  become: yes
  file:
    path: '{{ minikube_install_dir }}/{{ helm_name }}'
    state: absent

- name: Remove config files
  become: yes
  file:
    path: '{{ user_home }}/.config/{{ helm_name }}'
    state: absent

- name: Remove plugin files
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '{{ user_home }}/.local/share/{{ helm_name }}'
    - '{{ user_home }}/.helm'
