---

- name: set facts for helm
  set_fact:
    "user_home": "{{ lookup('env','HOME') }}"

- name: Check if helm is installed
  stat:
    path: '{{ minikube_install_dir }}/{{ helm_name }}'
  register: helm_installed

- name: Uninstall Helm
  block:
    - name: Reset Helm (uninstall Tiller)
      command: helm reset

    - name: Remove Helm binary
      file:
        path: '{{ minikube_install_dir }}/{{ helm_name }}'
        state: absent
      become: yes

    - name: Remove Helm link
      file:
        path: '{{ minikube_install_dir }}/{{ helm_name }}-*
        state: absent
      become: yes

    - name: Remove config files
      file:
        path: '{{ user_home }}/.config/{{ helm_name }}'
        state: absent
      become: yes

    - name: Remove Helm Repository Cache
      file:
        path:  '{{ user_home }}/.cache'
        state: absent
      become: yes
      
  when: helm_installed.stat.exists == true