---

- name: set facts for helm
  set_fact:
    "user_home": "{{ lookup('env','HOME') }}"

- name: Reset Helm (uninstall Tiller)
  command: helm reset

- name: Find all files with helm in name
  find:
    paths: "{{ minikube_install_dir }}"
    patterns: '{{ helm_name }}*'
  register: files_to_delete

- name: Remove all Helm files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

#   file:
#     path: '{{ minikube_install_dir }}/{{ helm_name }}'
#     state: absent
#   become: yes

# - name: Remove Helm link
#   file:
#     path: '{{ minikube_install_dir }}/{{ helm_name }}-*'
#     state: absent
#   become: yes

- name: Remove config files
  file:
    path: '{{ user_home }}/.config/{{ helm_name }}'
    state: absent
  become: yes

- name: Remove Helm Repository Cache
  file:
    path:  '{{ user_home }}/.cache'
    state: absent
  become: yes