image: ubuntu:18.04

before_script:
    - apt-get update
    - apt-get install -y bash python apt-transport-https ca-certificates curl software-properties-common
    

test_ubuntu_latest:
  tags:
  - docker-executor
  script:  
  - apt-add-repository --yes --update ppa:ansible/ansible 
  - apt-get -y install ansible
  - ansible-playbook -i hosts deploy_tangoenv.yml
  
  
test_ubuntu_16:
  image: ubuntu:16.04
  tags:
  - docker-executor
  script:
  - apt-add-repository --yes --update ppa:ansible/ansible 
  - apt-get -y install ansible
  - ansible-playbook -i hosts deploy_tangoenv.yml
  
  
test_debian_stretch-slim:
  image: debian:stretch-slim
  tags:
  - docker-executor
  script:
  - echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" >> /etc/apt/sources.list
  - apt-get install gnupg2 -y
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 93C4A3FD7BB9C367
  - apt-get update
  - apt-get -y install ansible
  - ansible-playbook -i hosts deploy_tangoenv.yml
