image: ska-registry.av.it.pt/ska-docker/tango-builder:latest

test:
  tags:
  - docker-executor
  script:
  - apt-add-repository --yes --update ppa:ansible/ansible 
  - apt-get -y install ansible
  - ansible-playbook -i hosts deploy_tangoenv.yml