---

- name: deploy_tangoenv
  hosts: development
  vars:
    build_tango: 'yes'
    install_pytango: 'yes'
    install_ide: 'yes'
    install_ska_docker: 'yes'
    start_tango: 'yes'
    update_hosts: 'yes'
  become: yes
  roles:
    - ide
    - tango
    - pytango
    - ska-docker
    - updatehosts
  environment: "{{ minikube_environment_vars }}"
