---
- name: deploy_runners
  hosts: localhost
  vars:
    build_tango: 'yes'
    install_pytango: 'yes'
    install_ide: 'yes'
    install_ska_docker: 'yes'
    start_tango: 'yes'
    update_hosts: 'yes'
    executor: 'docker'
    docker_image: 'docker:19.03.1'
  become: true
  become_method: sudo
  become_flags: '-E -S -n'
  roles: 
    - ska-docker
    - updatehosts
    - runner

