- name: Start ElasticDB
  hosts: localhost
  tasks:
  - name: Create a volume
    docker_volume:
      name: elastic_volume
  - name: Create a network
    docker_network:
      name: network_one
  - name: Elastic DB 1 UP
    docker_container:
      name: db_1
      domainname: db_1
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
      volumes:
        - "elastic_volume:/usr/share/elasticsearch/data"
      ports:
        - "9200:9200"
        - "9300:9300"
      env:
        discovery.type: "single-node"
      networks:
        - name: network_one
      
      