---

- name: k8s_create_inventory
  hosts: localhost
  become: true
  become_method: sudo
  become_flags: '-E -S -n'
  vars:
    cluster_name: 'mycluster'
    ips: '192.168.100.25 192.168.100.26'
    kubespray_dir: '~/tmp/kubespray'
  tasks:
    - name: get local user
      shell: "cat /etc/passwd | grep 1000 | cut -d: -f1" 
      args: 
      register: user

    - name: Install dependencies
      apt:
        name:
            - python-pip
            - python3-pip
        state: latest
        force: yes 
        update_cache: yes

    - name: Check if kubespray is already cloned
      stat:
              path: "{{kubespray_dir}}"
      register: kubespray_dir_info

    - fail:
            msg: "Kubespray already exists at {{kubespray_dir}}. Do you really want to create an inventory? Suggestion: run `make cluster` with your variables." 
            when: kubespray_dir_info.stat.exists and kubespray_dir_info.stat.isdir     

    - git:
        repo: 'https://github.com/kubernetes-sigs/kubespray.git'
        dest: "{{kubespray_dir}}"
        version: '{{ kube_spray_version }}'

    - name: Change permissions of temporary Kubespray directory
      file: 
        path: "{{kubespray_dir}}"
        owner: "{{ user.stdout }}"
        group: "{{ user.stdout }}"

    - name: Install requirements
      shell: |
        cd "{{kubespray_dir}}"/
        pip install -r requirements.txt
        pip3 install -r contrib/inventory_builder/requirements.txt

    # Copy ``inventory/sample`` as ``inventory/{{cluster_name}}``
    # Update Ansible inventory file with inventory builder
    - name: Create config file
      shell: |
        #!/bin/bash 
        cd "{{kubespray_dir}}"
        cp -rfp inventory/sample inventory/{{cluster_name}} 
        CONFIG_FILE=inventory/{{cluster_name}}/hosts.yaml python3 contrib/inventory_builder/inventory.py {{ ips }}

    - name: Set kube-version
      lineinfile:
        path: "{{ kubespray_dir }}/inventory/{{cluster_name}}/group_vars/k8s-cluster/k8s-cluster.yml"
        regexp: '^kube_version:'
        line: 'kube_version: {{k8s_version}}'

    - name: Set helm-enabled
      lineinfile:
        path: "{{kubespray_dir}}/inventory/mycluster/group_vars/k8s-cluster/addons.yml"
        regexp: '^helm_enabled:'
        line: 'helm_enabled: true'

    - name: Set helm-version
      lineinfile:
        path: "{{kubespray_dir}}/inventory/mycluster/group_vars/k8s-cluster/addons.yml"
        regexp: '^helm_version:'
        line: 'helm_version: {{helm_version}}'

    - name: Set kubeconfig_localhost
      lineinfile:
        path: "{{kubespray_dir}}/inventory/{{cluster_name}}/group_vars/k8s-cluster/k8s-cluster.yml"
        regexp: '^kubeconfig_localhost:'
        line: 'kubeconfig_localhost: true'

    - name: Set kubectl_localhost
      lineinfile:
        path: "{{kubespray_dir}}/inventory/{{cluster_name}}/group_vars/k8s-cluster/k8s-cluster.yml"
        regexp: '^kubectl_localhost:'
        line: 'kubectl_localhost: true'

    - debug:
        msg: 
        - "The following command installs the cluster:"
        - "cd {{kubespray_dir}} && ansible-playbook --flush-cache -u remote_machine_username -b -i inventory/{{cluster_name}}/hosts.yaml cluster.yml l --extra-vars 'ansible_ssh_private_key_file=/home/ubuntu/cloud.key'"
        - "Save inventory folder: {{kubespray_dir}}/inventory/{{cluster_name}}"
