---
- name: k8s_create_inventory
  hosts: all
  become: true
  become_method: sudo
  become_flags: '-E -S -n'
  tasks:
  - name: disable fingerprint checking that may be enabled; when enabled, causes ssh issues
    become: yes
    command: authconfig --disablefingerprint --update
  - git:
      repo: 'https://github.com/kubernetes-sigs/kubespray.git'
      dest: /usr/src/kubespray
      version: '{{ kube_spray_version }}'

- name: Include a cluster play from kubespray
  include: /usr/src/kubespray/cluster.yml
