---
# not all tasks should be run as root
- name: Install Docker
  hosts:
    - localhost
  roles:
    - docker

- name: Deploy kubectl
  hosts:
    - localhost
  become: yes
  roles:
    - kubectl

# not all tasks should be run as root
- name: Install helm
  hosts:
    - localhost
  roles:
    - helm

- name: k8s_deploy_components
  hosts: localhost
  become: true
  become_method: sudo
  become_flags: '-E -S -n'
  vars:
    k8s_master_uri: 'https://192.168.93.19:6443'
    master_cert: 'XXXXXX'
    dex_issuer: 'http://192.168.93.19:32000'
    dex_redirectURI: http://192.168.93.19:32000/callback 
    gitlab_client_id: '417ea12283741e0d74b22778d2dd3f5d0dcee78828c6e9a8fd5e8589025b8d2f'
    gitlab_client_secret: '27a5830ca37bd1956b2a38d747a04ae9414f9f411af300493600acc7ebe6107f'
    dex_k8s_authenticator_redirectURI: 'http://192.168.93.19:31000/callback/mycluster'
  tasks:
    - include: roles/helm/tasks/main.yml
    - include: roles/dex/tasks/main.yml

    - name: Install traefik
      hosts: localhost
      become: true
      become_method: sudo
      become_flags: '-E -S -n'
      shell: |
        helm init
        helm repo add stable https://kubernetes-charts.storage.googleapis.com/
        helm install stable/traefik --name traefik0 --namespace kube-system --set externalIP={{ansible_default_ipv4.address}}



  
