- name: Install Docker
  shell: curl -sSL https://get.docker.com/ | sh

- name: Create daemon.json file
  copy:
   dest: /etc/docker/daemon.json
   content: |
    {
      "default-address-pools":
      [
        {"base":"172.17.0.0/16","size":24}
      ]
    }

- name: Start and enable docker
  shell: systemctl start docker && systemctl enable docker

- name: Install the latest version of GitLab Runner
  shell: curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64

- name: Permissions to execute
  shell: chmod +x /usr/local/bin/gitlab-runner

- name: Create gitlabrunner user
  shell: useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash

- name: Install GitLab runner service
  shell: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner

- name: Register gitlab-runner
  shell: |
    gitlab-runner register \
      --non-interactive \
      --request-concurrency 3 \
      --url "https://gitlab.com/" \
      --registration-token "{{token}}" \
      --executor "{{executor}}" \
      --docker-image docker:19.03.1 \
      --description "{{runnername}}" \
      --tag-list "{{taglist}}" \
      --run-untagged="true" \
      --locked="false" \
      --access-level="not_protected" \
      --docker-privileged = "true"

- name: Replace volumes var
  replace:
    path: /etc/gitlab-runner/config.toml
    regexp: '"/cache"'
    replace: '"/cache","/var/run/docker.sock:/var/run/docker.sock","/builds:/builds:rw"'

- name: Run GitLab runner service
  shell: gitlab-runner start
