## need to be merged with install.yml!

- name: Install the latest version of GitLab Runner
  shell: curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64

- name: Permissions to execute
  shell: chmod +x /usr/local/bin/gitlab-runner

- name: Check that the service has already been installed
  stat:
    path: /etc/systemd/system/gitlab-runner.service
  register: stat_config

- name: Install GitLab runner service
  shell: gitlab-runner install --user=root 
  when: stat_config.stat.exists == False

- name: Add GitLab’s official repository
  shell: |
    gitlab-runner register \
      --non-interactive \
      --url "https://gitlab.com/" \
      --registration-token "{{token}}" \
      --executor "{{executor}}" \
      --docker-image {{docker_image}} \
      --description "{{name}}" \
      --tag-list "{{taglist}}" \
      --run-untagged="true" \
      --locked="false" \
      --access-level="not_protected"

- name: Replace volumes var
  replace:
    path: /etc/gitlab-runner/config.toml
    regexp: '"/cache"'
    replace: '"/cache","/var/run/docker.sock:/var/run/docker.sock","/builds:/builds:rw"'
  when: executor == 'docker'

- name: Replace volumes var
  replace:
    path: /etc/gitlab-runner/config.toml
    regexp: 'privileged = false'
    replace: 'privileged = true'
  when: executor == 'docker'
  ignore_errors: yes

- name: Create daemon.json file
  copy:
   dest: /etc/docker/daemon.json
   content: |
    {
      "default-address-pools":
      [
        {"base":"172.17.0.0/16","size":24}
      ]
    }

- name: restart and docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: true
  when: executor == 'docker'

- name: Run GitLab runner service
  shell: |
    gitlab-runner start
