---
- hosts: kubernetes-master-nodes
  become: yes
  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull

  - name: Resetting kubeadm
    shell: kubeadm reset -f

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --apiserver-advertise-address {{ ansible_eth0.ipv4.address }} --pod-network-cidr=10.244.0.0/16 --apiserver-cert-extra-sans {{ dns }}

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  - name: Download helm install script
    get_url:
      url: https://raw.githubusercontent.com/helm/helm/master/scripts/get
      dest: /root/helm.sh
      mode: '0700'

  - name: Replace "/usr/local/bin" by "/bin"
    replace:
      path: /root/helm.sh
      regexp: '/usr/local/bin'
      replace: "/bin"

  - name: Install Helm
    shell: "/root/helm.sh"
    args:
      executable: /bin/bash

  - name: Initialise Helm
    shell: "helm init --client-only"
    args:
      executable: /bin/bash

  - name: Tidy up Helm tmp
    file:
      path: '/root/helm.sh'
      state: absent

  - name: Install tiller plugin
    shell: "helm plugin install https://github.com/rimusz/helm-tiller"
    args:
      executable: /bin/bash