---
- name: Obtain Kubernetes cluster join command
  shell: kubeadm token create --print-join-command
  register: k8s_token
  when: node_role == 'master'

- name: Resetting kubeadm
  shell: kubeadm reset -f
  when: node_role == 'worker'

- name: Joining worker nodes with kubernetes master
  shell: "{{ hostvars[groups['kubernetes_master_nodes'][0]]['k8s_token'].stdout }}"
  when: node_role == 'worker'
