---
- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: remove .novalocal from /etc/hostname
  replace:
    path: /etc/hostname
    regexp: '.novalocal'
    replace: ""

- name: Replace hosts file
  copy:
   dest: /etc/hosts
   content: |
    127.0.0.1   {{ inventory_hostname }} localhost localhost.localdomain localhost4 localhost4.localdomain4
    ::1         {{ inventory_hostname }} localhost localhost.localdomain localhost6 localhost6.localdomain6

- name: Delete hostname set and update from cloud-init
  lineinfile:
    dest: /etc/cloud/cloud.cfg
    regexp: "hostname"
    state: absent
    
- name: remove cloud-init
  yum:
    name: 'cloud-init'
    state: absent

- name: install libselinux-python
  yum:
    name: 'libselinux-python'
    state: latest

- name: Disabling Swap on all nodes
  shell: /usr/sbin/swapoff -a

- name: Commenting Swap entries in /etc/fstab
  replace:
   path: /etc/fstab
   regexp: '(.*swap*)'
   replace: '#\1'

- name: Check if firewalld service exists
  stat: path=/usr/lib/systemd/system/firewalld.service
  register: service_status

- name: Stopping and Disabling the firewalld
  service:
   name: firewalld
   state: stopped
   enabled: no
  when: service_status.stat.exists

- name: Disable SELinux
  selinux:
    state: disabled

- name: Enabling Bridge Firewall Rule
  copy:
   dest: /etc/sysctl.d/k8s.conf
   content: |
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1

- name: Reload Firewall Rule
  shell: "sysctl --system"