---
- name: Install python python-dev python-pkgconfig python3-pymysql mysql-server mysql-client python-mysqldb (Ubuntu 16.04) (WARNING package names are deprecated on modern distros)
  apt:
    name:
        - python
        - python-dev 
        - python-pkgconfig
        - python3-pymysql
        - mysql-server
        - mysql-client
        - python-mysqldb
    state: latest
    force: yes 
    update_cache: yes
  when: 
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '16.04'
    - install_mysql == 'yes'

- name: install libmysqlclient-dev (Ubuntu 16.04) (WARNING package names are deprecated on modern distros)
  apt:
    name:
        - libmysqlclient-dev
    state: latest
    force: yes 
    update_cache: yes
  when: 
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '16.04'
    - install_mysql == 'yes'

- name: Install python python-dev python-pkgconfig python3-pymysql default-mysql-server default-mysql-client python-mysqldb
  apt:
    name:
        - python
        - python-dev 
        - python-pkgconfig
        - python3-pymysql
        - default-mysql-server
        - default-mysql-client
        - python-mysqldb
    state: latest
    force: yes 
    update_cache: yes
  when:
    - ansible_distribution_version != '16.04'
    - install_mysql == 'yes'

- name: install default-libmysqlclient-dev
  apt:
    name:
        - default-libmysqlclient-dev
    state: latest
    force: yes 
    update_cache: yes
  when: 
    - ansible_distribution_version != '16.04'
    - install_mysql == 'yes'

- name: copy .my.cnf
  copy:
    src: "{{playbook_dir}}/roles/mysqlserver/files/.my.cnf"
    dest:  ~/.my.cnf
    mode: 0644
  when: install_mysql == 'yes'

- name: Copy sql_mode.cnf
  copy:
    src: "{{playbook_dir}}/roles/mysqlserver/files/sql_mode.cnf"
    dest: /etc/mysql/conf.d
  when: install_mysql == 'yes'

# is it working?
- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: yes
  when: 
    - install_mysql == 'yes' 
    - start_mysql_server == 'yes'
