---

- name: Create directory build_pytango_dir
  file:
    path: /build_pytango_dir
    state: directory

- name: Copy Pipfile
  copy:
    src: "{{playbook_dir}}/roles/pytango/files/Pipfile"
    dest:  /build_pytango_dir/Pipfile
    force: yes
  when: install_pytango == 'yes'

- name: Copy Pipfile.lock
  copy:
    src: "{{playbook_dir}}/roles/pytango/files/Pipfile.lock"
    dest:  /build_pytango_dir/Pipfile.lock
    force: yes
  when: install_pytango == 'yes'

- name: Install libboost-python-dev python3-dev python3-pip python-apt virtualenv apt for pytango
  apt:
    name:
        - libboost-python-dev 
        - python3-dev 
        - python3-pip
        - python-apt
        - virtualenv
    state: latest
    force: yes 
    update_cache: yes
  when: install_pytango == 'yes'

- name: Temporary fix - install libtango8v5 for Ubuntu-16
  apt:
    name:
      - libtango8v5
  ignore_errors: True

- name: Temporary fix - install libtango9 for Ubuntu-18
  apt:
    name:
      - libtango9
  ignore_errors: True

- name: Copy environment.sh
  copy:
    src: "{{playbook_dir}}/roles/pytango/files/environment.sh"
    dest: /etc/profile.d/environment.sh
    mode: 0755
    force: yes
  when: install_pytango == 'yes'

- name: Install pytango on virtualenv with pipenv
  shell: |
    cd /build_pytango_dir
    export LC_ALL=C.UTF-8 \
      LANG=C.UTF-8 \
      PIPENV_TIMEOUT=900 \
      PATH=/venv/bin:$PATH \
      VIRTUAL_ENV=/venv \
      PIPENV_VERBOSITY=-1 \
      PIPENV_NOSPIN=1
    rm -r -f /venv
    pwd
    virtualenv -p /usr/bin/python3 /venv
    pip3 install pipenv
    pipenv install --dev
  when: install_pytango == 'yes'
