---

- name: Create directory build_pytango_dir
  file:
    path: /build_pytango_dir
    state: directory

- name: Copy Pipfile
  copy:
    src: "{{playbook_dir}}/roles/pytango/files/Pipfile"
    dest:  /build_pytango_dir/Pipfile
    force: yes
  when: install_pytango == 'yes'

- name: Copy Pipfile.lock
  copy:
    src: "{{playbook_dir}}/roles/pytango/files/Pipfile.lock"
    dest:  /build_pytango_dir/Pipfile.lock
    force: yes
  when: install_pytango == 'yes'

- name: Copy environment.sh
  copy:
    src: "{{playbook_dir}}/roles/pytango/files/environment.sh"
    dest: /etc/profile.d/environment.sh
    mode: 0755
    force: yes
  when: install_pytango == 'yes'

- name: Install dependencies
  apt:
    name:
        - libboost-python-dev 
        - python3-dev 
        - python3-pip
        - python-apt
        - virtualenv
        - dpkg-dev
        - libffi-dev
        - libreadline-gplv2-dev 
        - libncursesw5-dev 
        - libssl-dev 
        - libsqlite3-dev 
        - tk-dev 
        - libgdbm-dev 
        - libc6-dev 
        - libbz2-dev
    state: latest
    force: yes 
    update_cache: yes
  when: install_pytango == 'yes'

- name: Check if python3.7 exists
  stat: 
    path: /usr/local/bin/python3.7
  register: python_exe

- name: Install Python {{PYTHON_VERSION}}
  shell: |
    mkdir -p /usr/src/python
    cd /usr/src/python
    curl https://www.python.org/ftp/python/{{PYTHON_VERSION}}/Python-{{PYTHON_VERSION}}.tgz --output python37.tgz
    tar xf python37.tgz
    cd Python-{{PYTHON_VERSION}}/
    ./configure
    make
    make install
    rm -r /usr/src/python
  when: 
    - ansible_distribution_release != "buster"
    - install_pytango == 'yes'
    - python_exe.stat.exists == false

- name: Check libboost
  shell: |
    if test -f "/usr/lib/x86_64-linux-gnu/libboost_python3-py37.so"; then
        ln -sf /usr/lib/x86_64-linux-gnu/libboost_python3-py37.so /usr/lib/x86_64-linux-gnu/libboost_python-py37.so
        ln -sf /usr/lib/x86_64-linux-gnu/libboost_python3-py37.so /usr/local/lib/libboost_python-py37.so
    fi

    if test -f "/usr/lib/x86_64-linux-gnu/libboost_python3-py36.so"; then
        ln -sf /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so /usr/lib/x86_64-linux-gnu/libboost_python-py37.so
        ln -sf /usr/lib/x86_64-linux-gnu/libboost_python3-py36.so /usr/local/lib/libboost_python-py37.so
    fi

    if test -f "/usr/lib/x86_64-linux-gnu/libboost_python-py35.so"; then
        ln -sf /usr/lib/x86_64-linux-gnu/libboost_python-py35.so /usr/lib/x86_64-linux-gnu/libboost_python-py37.so
        ln -sf /usr/lib/x86_64-linux-gnu/libboost_python-py35.so /usr/local/lib/libboost_python-py37.so
    fi

    if test -f "/usr/lib/x86_64-linux-gnu/libz.so"; then
        ln -sf /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/libz.so
    fi

- name: Install pytango
  shell: |
    cd /build_pytango_dir
    export LC_ALL=C.UTF-8 \
      LANG=C.UTF-8 \
      PIPENV_TIMEOUT=900 \
      PATH=/venv/bin:$PATH \
      VIRTUAL_ENV=/venv \
      PIPENV_VERBOSITY=-1 \
      PIPENV_NOSPIN=1
    rm -r -f /venv
    pwd
    virtualenv -p python3.7 /venv
    pip3 install pipenv
    pipenv install --dev
  when: 
    - install_pytango == 'yes'