- name: set fact
  set_fact:
    "localuser": "{{ lookup('env','USER') }}"

- name: Install make
  apt:
    name:
    - make
    update_cache: yes

- name: Check if skampi exists
  stat: 
    path: /usr/src/skampi/Makefile
  register: skampiDir

- name: Creates directory /usr/src/skampi
  file:
    path: /usr/src/skampi
    state: directory
  when: skampiDir.stat.exists == false

- git:
    repo: 'https://gitlab.com/ska-telescope/skampi.git'
    dest: /usr/src/skampi
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"

- name: Change file ownership, group and permissions
  file:
    path: /usr/src/skampi
    owner: '{{ localuser }}'
    group: '{{ localuser }}'

- name: Start the integrated system
  become_user: "{{ localuser }}"
  shell: |
    cd /usr/src/skampi
    make deploy_all KUBE_NAMESPACE=integration 
    kubectl get all,pv,pvc,ingress -n integration