concurrent = 3
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "skampi-runner"
  url = "https://gitlab.com/"
  token = "{{token}}"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "{{docker_image}}"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache","/var/run/docker.sock:/var/run/docker.sock", "/builds:/builds:rw"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]