dependencies: []
galaxy_info:
  author: lmickh
  description: Install and run Elasticsearch as Docker container.
  license: MIT
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - elasticsearch
