all:
  hosts:
    node1:
      ansible_host: 192.168.100.25
      ip: 192.168.100.25
      access_ip: 192.168.100.25
    node2:
      ansible_host: 192.168.100.26
      ip: 192.168.100.26
      access_ip: 192.168.100.26
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
