{
 "title": "Summarised Docker Metrics",
 "description": "Docker Monitoring Template",
 "tags": [
  "docker",
  "prometheus, ",
  "node-exporter"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "ExporterType", "label": "Exporter Type", "query": "label_values(job)" },
   { "name": "DockerTarget", "label": "docker_target", "query": "label_values(instance)" },
   { "name": "DS_PROMETHEUS", "query": "Prometheus" }
  ]
 },
 "panels": [
  { "title": "Containers & Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Engine Daemon Container States",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (engine_daemon_container_states_containers{job=\"docker\",instance=~\"$DockerTarget\"})"
    }
   ]
  },
  {
   "title": "Engine Daemon Container States",
   "type": "table",
   "description": "This table provides all the daemon  container states, with links to the instances.",
   "gridPos": { "h": 23, "w": 6, "x": 17, "y": 1 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "engine_daemon_container_states_containers{instance=~\"$DockerTarget\"}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Online Docker Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(up{instance=~\"$DockerTarget\"})"
    }
   ]
  },
  {
   "title": "Paused Docker Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers{state=\"paused\"})"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "description": "SKA Systems 1 cluster Memory usage %",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{cluster=\"ska-systems1\"}) - sum(node_memory_MemFree_bytes{cluster=\"ska-systems1\"} +node_memory_Buffers_bytes{cluster=\"ska-systems1\"} + node_memory_Cached_bytes{cluster=\"ska-systems1\"}) ) / sum(node_memory_MemTotal_bytes{cluster=\"ska-systems1\"}) * 100"
    }
   ]
  },
  {
   "title": "Packets Transmitted by Docker Devices",
   "type": "graph",
   "description": "node_network_transmit_bytes_total{device=\"docker0\"}\n",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Packets" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_transmit_packets_total{device=\"docker0\"}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers{state=\"running\",instance=~\"$DockerTarget\"})"
    }
   ]
  },
  {
   "title": "Stopped Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(engine_daemon_container_states_containers{state=\"stopped\",instance=~\"$DockerTarget\"})"
    }
   ]
  },
  {
   "title": "Data throughput via Docker Network Devices",
   "type": "graph",
   "description": "node_network_transmit_bytes_total{device=\"docker0\"}\n",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"docker0\"}[1m])*60",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Data throughput via Docker Network Devices",
   "type": "graph",
   "description": "node_network_transmit_bytes_total{device=\"docker0\"}\n",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"docker0\"}[1m])*60",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}