- name: Check if docker prometheus exporter is already set
  wait_for:
    port: 9323
    timeout: 3
  register: check_port
  ignore_errors: true

- debug:
    var: check_port

- name: Check that the daemon.json exists
  stat:
    path: /etc/docker/daemon.json
  register: stat_result

- name: Create daemon.json file
  copy:
   dest: /etc/docker/daemon.json
   content: |
    {
      "metrics-addr" : "127.0.0.1:9323",
      "experimental" : true
    }
  when: not stat_result.stat.exists and check_port.state != "started"

- name: Load daemon.json
  include_vars:
    file: /etc/docker/daemon.json
    name: daemon
  when: check_port.state != "started"

- debug:
    var: daemon
  when: check_port.state != "started"

- name: Configure metrics-addr
  set_fact:
    daemon: "{{ daemon | default([]) | combine({ 'metrics-addr': '127.0.0.1:9323' }) }}"
  when: daemon['metrics-addr'] is not defined and check_port.state != "started"

- name: Configure experimental
  set_fact:
    daemon: "{{ daemon | default([]) | combine({ 'experimental': true }) }}"
  when: daemon['experimental'] is not defined and check_port.state != "started"

- debug:
    var: daemon
  when: check_port.state != "started"

- name: Write daemon.json
  copy: 
    content: "{{ daemon | to_nice_json }}" 
    dest: /etc/docker/daemon.json
  when: check_port.state != "started"

- name: restart and docker
  systemd:
    name: docker
    state: restarted
  when: check_port.state != "started"