---

- name: make sure grafana configuration directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "/etc/grafana/provisioning/datasources"
    - "/etc/grafana/provisioning/dashboards/gitlab-runners"
    - "/etc/grafana/provisioning/notifiers"

- name: Copy up resource files
  copy:
    src: "{{ role_path }}/files/dashboards/gitlab-runners/{{ item }}"
    dest: "/etc/grafana/provisioning/dashboards/gitlab-runners/{{ item }}"
  with_items:
    - simple.json

- name: Write dashboards provisioning config file
  template:
    src: dashboards-gitlab-runners-dashboard.yml.j2
    dest: /etc/grafana/provisioning/dashboards/gitlab-runners-dashboard.yml
    mode: 0640
