---

- name: make sure grafana configuration directories exist
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    # - "/etc/grafana/dashboards/elasticstack-dashboard"
    - "/etc/grafana/provisioning/datasources"
    - "/etc/grafana/provisioning/dashboards/elasticstack-dashboard"
    - "/etc/grafana/provisioning/notifiers"

- name: Copy up resource files
  copy:
    src: "{{ role_path }}/files/dashboards/elasticstack/{{ item }}"
    dest: "/etc/grafana/provisioning/dashboards/elasticstack-dashboard/{{ item }}"
  with_items:
    - dashboard.json

- name: Write dashboards provisioning config file
  template:
    src: dashboards-elasticstack-dashboard.yml.j2
    dest: /etc/grafana/provisioning/dashboards/elasticstack-dashboard.yml
    mode: 0640

# - name: copy grafana SSL certificate file
#   copy:
#     src: "{{ grafana_crt }}"
#     dest: "/etc/grafana/elasticstack-dashboard.crt"
#     owner: "{{ grafana_uid }}"
#     group: "{{ grafana_uid }}"
#     mode: 0640
#   when:
#     - grafana_crt | length > 0
#     - dashboard_protocol == "https"

# - name: copy grafana SSL certificate key
#   copy:
#     src: "{{ grafana_key }}"
#     dest: "/etc/grafana/elasticstack-dashboard.key"
#     owner: "{{ grafana_uid }}"
#     group: "{{ grafana_uid }}"
#     mode: 0440
#   when:
#     - grafana_key | length > 0
#     - dashboard_protocol == "https"

# - name: generate a Self Signed OpenSSL certificate for dashboard
#   shell: |
#     test -f /etc/grafana/elasticstack-dashboard.key -a -f /etc/grafana/elasticstack-dashboard.crt || \
#     (openssl req -new -nodes -x509 -subj '/O=IT/CN=elasticstack-grafana' -days 3650 -keyout /etc/grafana/elasticstack-dashboard.key -out /etc/grafana/elasticstack-dashboard.crt -extensions v3_ca && \
#     chown {{ grafana_uid }}:{{ grafana_uid }} /etc/grafana/elasticstack-dashboard.key /etc/grafana/elasticstack-dashboard.crt)
#   when:
#     - dashboard_protocol == "https"
#     - grafana_key | length == 0 or grafana_crt | length == 0

