---
# tasks file for prometheus

- name: Install distutils
  apt:
    pkg:
      - python3-distutils
      - python3-requests
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian" and (mode == "server" or mode == "all" or mode == "docker")

- name: Fix pip
  block:

  - name: Install packages required for docker (apt)
    apt:
      name: ['python3-pip']
      state: present
    when: ansible_os_family == "Debian"

  - name: Ensure dnf installed
    yum:
      name: "dnf"
      state: present
    when: ansible_distribution == "CentOS"

  - name: Install packages required for docker (dnf)
    dnf:
      name: ['python-pip', 'python3-pip']
      state: present
    when: ansible_os_family == "RedHat"

  - name: uninstall docker dependencies
    pip:
      name: ['docker-py', 'docker-pycreds']
      executable: pip3
      state: absent

  - name: install docker dependencies
    pip:
      executable: pip3
      name: docker

  when: mode == "server" or mode == "all" or mode == "docker"

- name: pip self-update
  pip:
    name: pip
    state: latest
  when: mode == "server" or mode == "all" or mode == "docker"

- name: install certain python modules for docker
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: pip3
    state: present
  with_items:
  - { name: keystoneauth1, version: 3.1.0 }
  - { name: python-novaclient, version: 2.27.0 }
  - { name: rackspace-novaclient, version: 2.1 }
  - { name: python-heatclient, version: 2.0.0 }
  when: mode == "server" or mode == "all" or mode == "docker"

- include: blackbox_exporter.yml
  when: mode == "server" or mode == "all"

- include: runner_exporter.yml
  when: mode == "runner"

- include: docker_exporter.yml
  when: mode == "docker"

- include: grafana_ceph.yml
  when: mode == "server" or mode == "all"

- include: grafana_elasticstack.yml
  when: mode == "server" or mode == "all"

- include: grafana_kubernetes.yml
  when: mode == "server" or mode == "all"

- include: grafana_gitlab_runners.yml
  when: mode == "server" or mode == "all"

- include: grafana_cadvisor.yml
  when: mode == "server" or mode == "all"

- include: grafana_nodexporter.yml
  when: mode == "server" or mode == "all"

- include: gitlab_ci_pipelines_exporter.yml
  when: mode == "server" or mode == "all"

- include: grafana_alerts.yml
  when: mode == "server" or mode == "all"

# launch prom/alert/grafana after configuration
- include: server.yml
  when: mode == "server" or mode == "all"
  tags:
  - cron

- include: alert_manager.yml
  when: mode == "server" or mode == "all"
  tags:
  - cron

- include: grafana.yml
  when: mode == "server" or mode == "all"
  tags:
  - cron

- include: runner_exporter.yml
  when: mode == "runner"
