---
# tasks file for prometheus

- name: Download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: '0744'

- name: get-pip
  shell: |
    python3 /tmp/get-pip.py

- name: Install docker-py
  pip:
    name: docker-py
  become: yes
  
- include: server.yml
  when: mode == "server" or mode == "all"

- include: alert_manager.yml
  when: mode == "server" or mode == "all"

- include: blackbox_exporter.yml
  when: mode == "server" or mode == "all"

- include: grafana.yml
  when: mode == "server" or mode == "all"

- include: node_exporter.yml
  when: mode == "exporter" or mode == "all"
