---
- name: install libselinux-python
  yum:
    name: 
      - libselinux-python
      - prometheus-node-exporter
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: Install node_exporter
  become: yes
  apt:
    name:
        - prometheus-node-exporter
    state: latest
    force: yes 
    update_cache: yes
  when: 
    - ansible_distribution == 'Ubuntu'
