---
- name: install libselinux-python
  yum:
    name:
      - libselinux-python
      - prometheus-node-exporter
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: Configure /etc/apt/sources.list
  blockinfile:
    path: /etc/apt/sources.list
    block: |
      deb http://it.archive.ubuntu.com/ubuntu/ focal main universe restricted multiverse
      deb-src http://it.archive.ubuntu.com/ubuntu/ focal main universe restricted multiverse

      deb http://security.ubuntu.com/ubuntu focal-security main universe restricted multiverse
      deb-src http://security.ubuntu.com/ubuntu focal-security main universe restricted multiverse

      deb http://it.archive.ubuntu.com/ubuntu/ focal-updates main universe restricted multiverse
      deb-src http://it.archive.ubuntu.com/ubuntu/ focal-updates main universe restricted multiverse
  when:
    - ansible_distribution == 'Ubuntu'

- name: Install prometheus-node-exporter
  become: yes
  apt:
    name: prometheus-node-exporter
    state: present
    force: yes
    update_cache: yes
  when:
    - ansible_distribution == 'Ubuntu'

- name: Reboot
  reboot:
