---
- name: install libselinux-python
  yum:
    name: 'libselinux-python'
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat'

- name: Install node_exporter
  become: yes
  apt:
    name:
        - prometheus-node-exporter
    state: latest
    force: yes 
    update_cache: yes
  when: 
    - ansible_distribution == 'Ubuntu'

- name: Copy the Node Exporter systemd service file
  template:
    src: "{{playbook_dir}}/roles/prometheus/templates/node_exporter.service.j2"
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644

- name: Ensure Node Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: restarted
