---
# tasks file for prometheus

- name: ensure Prometheus configuration directory
  file:
    path: '{{ prometheus_config_dir }}'
    state: directory
    mode: 0755
  become: yes

- name: ensure Prometheus rules configuration directory
  file:
    path: '{{ prometheus_config_dir }}/rules/'
    state: directory
    mode: 0755
  become: yes

- name: Generate Prometheus configuration
  become: true
  template:
    src: "{{playbook_dir}}/roles/prometheus/templates/prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: "{{ localuser }}"
    group: "{{ localuser }}"
    mode: 0755

- name: alerting rules file
  template:
    src: "{{playbook_dir}}/roles/prometheus/templates/alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/ansible_managed.rules"
    owner: "{{ localuser }}"
    group: "{{ localuser }}"
    mode: 0755
  when:
    - prometheus_alert_rules != []

- name: copy basic rules
  copy:
    src: "{{playbook_dir}}/roles/prometheus/files/basic.rules"
    dest: "{{ prometheus_config_dir }}/rules/basic.rules"
    owner: "{{ localuser }}"
    group: "{{ localuser }}"
    mode: 0755

- name: Pull prometheus image {{prometheus_docker_tags}}
  docker_image:
    name: prom/prometheus
    tag: "{{prometheus_docker_tags}}"

- name: Start prometheus container
  docker_container:
    name: prometheus
    image: prom/prometheus
    state: started
    restart: yes
    restart_policy: on-failure
    ports:
     - "9090:9090"
    volumes:
      - "{{ prometheus_config_dir }}:/etc/prometheus:rw"
      - "/etc/hosts:/etc/hosts"
