---

- name: Install needed packages
  apt:
    pkg:
      - git
      - git-core
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
      - sudo
    state: present
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"

- name: Install pyenv
  become: yes
  become_user: "{{ localuser }}"
  shell: curl https://pyenv.run | bash
  args:
    creates: "{{ localhome }}/.pyenv"
    warn: false

- name: Add path etc to .bashrc.
  become: yes
  become_user: "{{ localuser }}"
  lineinfile:
    dest: "{{ localhome }}/.bashrc"
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
    - 'export PYENV_ROOT="$HOME/.pyenv"'
    - 'export PATH="$PYENV_ROOT/bin:$PATH"'
    - 'eval "$(pyenv init -)"'
    - 'eval "$(pyenv virtualenv-init -)"'

- name: Install default python version
  become: yes
  become_user: "{{ localuser }}"
  shell: "{{ localhome }}/.pyenv/bin/pyenv install {{ PYTHON_VERSION }}"
  args:
    creates: "{{ localhome }}/.pyenv/versions/{{ PYTHON_VERSION }}"

- name: Activate global pyenv's python version
  become: yes
  become_user: "{{ localuser }}"
  shell: "{{ localhome }}/.pyenv/bin/pyenv global {{ PYTHON_VERSION }}"