---
- name: resolve platform specific vars
  include_vars: '{{ driver_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/../../vars'
  loop_control:
    loop_var: driver_vars

- name: install Driver OS pkg dependencies
  become: "{{ 'no' if ansible_os_family == 'Darwin' else 'yes' }}"
  become_user: root
  with_items: '{{ minikube_driver_pkgs|default([]) }}'
  loop_control:
    loop_var: driver_pkg
  package:
    name: '{{ driver_pkg }}'
    state: present

- name: ensure target directory
  file:
    path: '{{ minikube_install_dir }}'
    state: directory
    mode: '0755'

- name: RedHat/Debian configuration for Driver
  block:
    - name: download docker-machine-driver-kvm2
      get_url:
        url: '{{ minikube_kvm2_driver_url }}'
        dest: '{{ minikube_install_dir }}/{{ minikube_kvm2_name }}-{{ minikube_version }}'
        mode: 0755

    - name: link installed docker-machine-driver-kvm2
      file:
        src: '{{ minikube_install_dir }}/{{ minikube_kvm2_name }}-{{ minikube_version }}'
        dest: '{{ minikube_install_dir }}/{{ minikube_kvm2_name }}'
        state: link
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Darwin configuration for Driver
  block:
    - name: download docker-machine-driver-hyperkit
      get_url:
        url: '{{ minikube_hyperkit_driver_url }}'
        dest: '{{ minikube_install_dir }}/{{ minikube_hyperkit_name }}-{{ minikube_version }}'
        owner: root
        group: wheel
        mode: '4755'

    - name: link installed docker-machine-driver-hyperkit
      file:
        src: '{{ minikube_install_dir }}/{{ minikube_hyperkit_name }}-{{ minikube_version }}'
        dest: '{{ minikube_install_dir }}/{{ minikube_hyperkit_name }}'
        state: link

    - name: fix up docker-machine-driver-hyperkit permissions
      file:
        path: '{{ minikube_install_dir }}/{{ minikube_hyperkit_name }}'
        owner: root
        group: wheel
        mode: '4755'
  when: ansible_os_family == "Darwin"
