#!/usr/bin/env ansible-playbook
---

- name: "Apply the common role to docker nodes"
  hosts:
    - docker-nodes
  become: yes
  become_method: sudo
  roles:
    - common

- name: "Apply the containerd role to the docker nodes"
  hosts:
    - docker-nodes
  become: yes
  roles:
    - role: containerd
      when: activate_nvidia|bool or activate_containerd|bool
  tags:
    - containerd

- name: "Show debug info"
  hosts:
    - docker-nodes
  become: yes
  tasks:
    - name: "Show docker nodes info"
      debug: var=hostvars[inventory_hostname]
      when: debug

- name: "Apply the docker role to the docker nodes"
  hosts:
    - docker-nodes
  become: yes
  roles:
    - docker
