---
- name: resolve platform specific vars
  include_vars: '{{ docker_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/../../vars'
  loop_control:
    loop_var: docker_vars

- name: Gather the os package facts
  package_facts:
    manager: auto

- name: uninstall minikube if needed (Debian)
  apt:
    name: minikube
    state: absent
  when: "ansible_os_family == 'Debian' and 'minikube' in ansible_facts.packages and ansible_facts.packages['minikube'][0].version != minikube_version[1:]"

- name: install minikube (Debian)
  apt:
    deb: '{{ minikube_deb_url }}'
  when: "ansible_os_family == 'Debian'"

- name: install minikube (Dawin)
  homebrew:
    name: 'minikube@{{ minikube_version[1:] }}'
    state: present
  when: "ansible_os_family == 'Darwin'"