---
- name: resolve platform specific vars
  include_vars: '{{ docker_vars }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/../../vars'
  loop_control:
    loop_var: docker_vars

- name: install minikube (Debian)
  apt:
    deb: '{{ minikube_deb_url }}'
    force: yes
  when: "ansible_os_family == 'Debian'"

- name: install minikube (Darwin)
  homebrew:
    name: 'minikube@{{ minikube_version[1:] }}'
    state: present
  when: "ansible_os_family == 'Darwin'"

- name: install minikube (CentOS)
  yum:
    name: '{{ minikube_rpm_url }}'
    state: present
    allow_downgrade: yes
  when: "ansible_os_family == 'RedHat'"
