#
- name: Remove Minikube
  import_tasks: remove.yml
  when: 
  - remove_cluster == 'yes'

- name: Stop Integrated System
  import_tasks: stop.yml
  when: 
  - stop_integrated_system == 'yes'

- name: Install Minikube
  import_tasks: minikube.yml
  when: 
  - deploy == 'yes'

- name: Start System
  import_tasks: start.yml
  when: 
  - deploy == 'yes'

- name: Logs
  import_tasks: logs.yml
  when: 
  - logs == 'yes'
