- name: Install make
  apt:
    name:
    - make
    update_cache: yes

- name: Check if k8s-integration exists
  stat: 
    path: /usr/src/k8s-integration/Makefile
  register: k8sDir

- name: Creates directory /usr/src/k8s-integration
  file:
    path: /usr/src/k8s-integration
    state: directory
  when: k8sDir.stat.exists == false

- git:
    repo: 'https://github.com/ska-telescope/k8s-integration.git'
    dest: /usr/src/k8s-integration
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"

- name: Linting the chart
  import_role:
    name: helm-lint
    tasks_from: one_chart
  when: helm_lint is defined and helm_lint == "yes"
  vars:
    directory: /usr/src/k8s-integration/chart

- name: Start the integrated system
  become_user: "{{ ansible_user }}"
  shell: |
    cd /usr/src/k8s-integration
    kubectl apply -f resources/traefik-minikube.yaml
    make deploy_all KUBE_NAMESPACE=integration 
    kubectl get all,pv,pvc,ingress -n integration
  when: start_integrated_system == 'yes'
