- name: Install make
  apt:
    name:
    - make
    update_cache: yes

- name: Check if skampi exists
  stat: 
    path: /usr/src/skampi/Makefile
  register: skampiDir

- name: Creates directory /usr/src/skampi
  file:
    path: /usr/src/skampi
    state: directory
  when: skampiDir.stat.exists == false

- git:
    repo: 'https://gitlab.com/ska-telescope/skampi.git'
    dest: /usr/src/skampi
    update: yes
    ssh_opts: "-o StrictHostKeyChecking=no"

- name: Linting the chart
  import_role:
    name: helm-lint
    tasks_from: one_chart
  when: helm_lint is defined and helm_lint == "yes"
  vars:
    directory: /usr/src/skampi/chart

- name: Change file ownership, group and permissions
  file:
    path: /usr/src/k8s-integration
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Start the integrated system
  become_user: "{{ ansible_user }}"
  shell: |
    cd /usr/src/skampi
    kubectl apply -f resources/traefik-minikube.yaml
    make deploy_all KUBE_NAMESPACE=integration 
    kubectl get all,pv,pvc,ingress -n integration
  when: start_integrated_system == 'yes'
