- name: Check if k8s-integration exists
  stat: 
    path: /usr/src/k8s-integration/Makefile
  register: k8sDir

- name: Stop the integrated system
  become_user: "{{ ansible_user }}"
  shell: |
    cd /usr/src/k8s-integration
    make delete KUBE_NAMESPACE=integration
    kubectl delete -f resources/traefik-minikube.yaml
  when: 
  - k8sDir.stat.exists == true
  - stop_integrated_system == 'yes'