heat_template_version: 2013-05-23
heat_stack_name: test-runner
description: TEST Runner

resources:
  GitLabRunnerNode:
    type: OS::Nova::Server
    content:
      ansible:
        file: '../../deploy_openstack_runner.yaml'
        extra-vars: "token='seyd2HjhP4TkVveTe4Fx' runnername='EngageSKA-AUTO-TMC-Runner' taglist='docker-executor,engageska,ska,tmc-prototype' executor='docker'"
    properties:
      image: 'Ubuntu 18.04 LTS Jan/2020'
      flavor: r1.medium
      key_name: tick-stack
      networks:
        - network: int_net
