---

- name: Install Desktop Environment (Ubuntu)
  apt:
    name: 
      - ubuntu-desktop
    update_cache: yes
  when:
    - install_ide == 'yes'
    - ansible_distribution == 'Ubuntu'

- name: Install Desktop Environment (Debian)
  apt:
    name: 
      - task-gnome-desktop
    update_cache: yes
  when:
    - install_ide == 'yes'
    - ansible_distribution == 'Debian'

- name: Install vscode
  apt:
    deb: "https://go.microsoft.com/fwlink/?LinkID=760868"
    force: yes
  when: install_ide == 'yes'

- name: Create directory pycharm
  file:
    path: /usr/src/pycharm
    state: directory
  
- name: Download Pycharm
  get_url:
    url: "https://download.jetbrains.com/python/pycharm-{{pycharm_version}}.tar.gz"
    dest:  /usr/src/pycharm/pycharm-{{pycharm_version}}.tar.gz
    mode: 0644
    force: yes
  when: install_ide == 'yes'

- name: Install Pycharm
  shell: |
    cd /usr/src/pycharm/
    tar xfz pycharm-{{pycharm_version}}.tar.gz -C /opt/
    echo run pycharm located with /opt/pycharm-{{pycharm_version}}/bin/pycharm.sh
  when: install_ide == 'yes'

## the following step allow to open a GUI from k8s to the server machine using ssh -X option
- name: Xserver needs to allow TCP connections
  blockinfile:
    path: /etc/gdm3/custom.conf
    block: |
      [security]
      DisallowTCP=false
  when: install_ide == 'yes'

- name: Disable xhost access control
  become: no
  command: xhost + 
  when: install_ide == 'yes'

- name: X11 UseLocalhost no
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      X11UseLocalhost no
  when: install_ide == 'yes'

