{
 "title": "Gitlab Runners Simple Dashboard",
 "description": "This dashboard is based on the Gitlab Runner Service Dashboard found at https://grafana.com/grafana/dashboards/2341",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "runner", "label": "Runner", "query": "label_values(runner)" }
  ]
 },
 "panels": [
  { "title": "$runner", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs running",
   "type": "graph",
   "description": "Currently active jobs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(gitlab_runner_jobs)", "legendFormat": "All jobs" }
   ]
  },
  {
   "title": "Gitlab Runner Failed Jobs",
   "type": "graph",
   "description": "Sum of all failed jobs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_failed_jobs_total{failure_reason=\"script_failure\"})",
     "legendFormat": "Script Failures"
    },
    {
     "expr": "sum(gitlab_runner_failed_jobs_total{failure_reason=\"job_execution_timeout\"})",
     "legendFormat": "Job Execution Timeouts"
    },
    {
     "expr": "sum(gitlab_runner_failed_jobs_total{failure_reason=\"runner_system_failure\"})",
     "legendFormat": "Runner System Failures"
    }
   ]
  },
  {
   "title": "Jobs pending",
   "type": "graph",
   "description": "Total number of Pipeline jobs in \"pending\" state over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs{state=\"pending\"})",
     "legendFormat": "Gitlab runner jobs pending"
    }
   ]
  },
  {
   "title": "Gitlab Runner Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (level)(irate(gitlab_runner_errors_total[1d])) * 100",
     "legendFormat": "\"{{level}}\" on these runners: {$runner}"
    }
   ]
  }
 ]
}