{
 "title": "Gitlab Runner monitoring",
 "description": "For the girlab runners exposed metrics (Autoscaling)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "runner",
    "query": "label_values(gitlab_runner_request_concurrency_exceeded_total, runner)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Runner Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "gitlab_runner_version_info" }
   ]
  },
  {
   "title": "Errors Total N (general)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(gitlab_runner_errors_total{level=\"error\",instance!~\"192.168.*\"}[1d])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runner errors Increase Number (general)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 10, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gitlab_runner_errors_total{level=\"error\",instance!~\"192.168.*\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Runner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Job failed Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(gitlab_runner_failed_jobs_total{runner=~\"$runner\",instance!~\"192.168.*\"}[1d])",
     "legendFormat": "{{failure_reason}} in {{instance}}({{runner}})"
    }
   ]
  },
  {
   "title": "Job running N",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, runner)(gitlab_runner_jobs{runner=~\"$runner\",instance!~\"192.168.*\"})",
     "legendFormat": "{{instance}}({{runner}})"
    }
   ]
  },
  {
   "title": "Jobs pending N",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_jobs{state=\"pending\",instance!~\"192.168.*\"}",
     "legendFormat": "{{instance}}({{runner}})"
    }
   ]
  },
  {
   "title": "Number of concurrent requests for a new job",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 10, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "gitlab_runner_request_concurrency{runner=~\"$runner\",instance!~\"192.168.*\"}",
     "legendFormat": "{{instance}}({{ runner }})"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "gitlab_runner_job_duration_seconds_sum{runner=~\"$runner\",instance!~\"192.168.*\"}/gitlab_runner_job_duration_seconds_count{runner=~\"$runner\",instance!~\"192.168.*\"}",
     "legendFormat": "{{instance}}({{runner}})"
    }
   ]
  },
  {
   "title": "Rate of concurrency exceeded total",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 10, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "irate(gitlab_runner_request_concurrency_exceeded_total{runner=~\"$runner\",instance!~\"192.168.*\"}[1d])",
     "legendFormat": "{{instance}}({{ runner }})"
    }
   ]
  },
  {
   "title": "API Request Statuses Total N",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (runner)(irate(gitlab_runner_api_request_statuses_total{runner=~\"$runner\"}[1d])) * 100\r",
     "legendFormat": "Runner={{ runner }}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  }
 ]
}