{
 "title": "Gitlab Runners Simple Dashboard",
 "description": "This dashboard is based on the Gitlab Runner Service Dashboard found at https://grafana.com/grafana/dashboards/2341",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "runner", "label": "Runner", "query": "label_values(runner)" }
  ]
 },
 "panels": [
  { "title": "$runner", "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs running",
   "type": "graph",
   "description": "Currently active jobs",
   "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gitlab_runner_jobs", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "Pipelines pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 4.8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ci_runner_builds{instance=~\"$runner\", state=\"pending\"}",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  {
   "title": "Pipelines pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 9.6, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ci_runner_builds{instance=~\"$runner\", state=\"pending\"}",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  {
   "title": "Pipelines pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 14.399999999999999, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ci_runner_builds{instance=~\"$runner\", state=\"pending\"}",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  {
   "title": "Pipelines pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 19.2, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ci_runner_builds{instance=~\"$runner\", state=\"pending\"}",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  {
   "title": "Pipelines pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 10 },
   "repeat": "runner",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ci_runner_builds{instance=~\"$runner\", state=\"pending\"}",
     "legendFormat": "{{executor_stage}}"
    }
   ]
  },
  {
   "title": "Pipeline Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 4.8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ci_runner_errors{instance=~\"$runner\"}[10m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Pipeline Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 9.6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ci_runner_errors{instance=~\"$runner\"}[10m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Pipeline Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 14.399999999999999, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ci_runner_errors{instance=~\"$runner\"}[10m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Pipeline Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 19.2, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ci_runner_errors{instance=~\"$runner\"}[10m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Pipeline Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 17 },
   "repeat": "runner",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ci_runner_errors{instance=~\"$runner\"}[10m])",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}